/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStationsRouteImport } from './routes/app.stations'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPredictionRouteImport } from './routes/app.prediction'
import { Route as AppLiveRouteImport } from './routes/app.live'
import { Route as AppGeoRouteImport } from './routes/app.geo'
import { Route as AppEnvironmentalRouteImport } from './routes/app.environmental'
import { Route as AppDevicesRouteImport } from './routes/app.devices'
import { Route as AppBloomRouteImport } from './routes/app.bloom'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAboutRouteImport } from './routes/app.about'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStationsRoute = AppStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionRoute = AppPredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppGeoRoute = AppGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentalRoute = AppEnvironmentalRouteImport.update({
  id: '/environmental',
  path: '/environmental',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppBloomRoute = AppBloomRouteImport.update({
  id: '/bloom',
  path: '/bloom',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bloom': typeof AppBloomRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/geo': typeof AppGeoRoute
  '/app/live': typeof AppLiveRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stations': typeof AppStationsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/about': typeof AppAboutRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bloom': typeof AppBloomRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/geo': typeof AppGeoRoute
  '/app/live': typeof AppLiveRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stations': typeof AppStationsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/about': typeof AppAboutRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bloom': typeof AppBloomRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/environmental': typeof AppEnvironmentalRoute
  '/app/geo': typeof AppGeoRoute
  '/app/live': typeof AppLiveRoute
  '/app/prediction': typeof AppPredictionRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stations': typeof AppStationsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/about'
    | '/app/admin'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/bloom'
    | '/app/devices'
    | '/app/environmental'
    | '/app/geo'
    | '/app/live'
    | '/app/prediction'
    | '/app/reports'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/stations'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/about'
    | '/app/admin'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/bloom'
    | '/app/devices'
    | '/app/environmental'
    | '/app/geo'
    | '/app/live'
    | '/app/prediction'
    | '/app/reports'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/stations'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/about'
    | '/app/admin'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/bloom'
    | '/app/devices'
    | '/app/environmental'
    | '/app/geo'
    | '/app/live'
    | '/app/prediction'
    | '/app/reports'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/stations'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stations': {
      id: '/app/stations'
      path: '/stations'
      fullPath: '/app/stations'
      preLoaderRoute: typeof AppStationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prediction': {
      id: '/app/prediction'
      path: '/prediction'
      fullPath: '/app/prediction'
      preLoaderRoute: typeof AppPredictionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/geo': {
      id: '/app/geo'
      path: '/geo'
      fullPath: '/app/geo'
      preLoaderRoute: typeof AppGeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/environmental': {
      id: '/app/environmental'
      path: '/environmental'
      fullPath: '/app/environmental'
      preLoaderRoute: typeof AppEnvironmentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bloom': {
      id: '/app/bloom'
      path: '/bloom'
      fullPath: '/app/bloom'
      preLoaderRoute: typeof AppBloomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/about': {
      id: '/app/about'
      path: '/about'
      fullPath: '/app/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBloomRoute: typeof AppBloomRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppEnvironmentalRoute: typeof AppEnvironmentalRoute
  AppGeoRoute: typeof AppGeoRoute
  AppLiveRoute: typeof AppLiveRoute
  AppPredictionRoute: typeof AppPredictionRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStationsRoute: typeof AppStationsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBloomRoute: AppBloomRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppEnvironmentalRoute: AppEnvironmentalRoute,
  AppGeoRoute: AppGeoRoute,
  AppLiveRoute: AppLiveRoute,
  AppPredictionRoute: AppPredictionRoute,
  AppReportsRoute: AppReportsRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStationsRoute: AppStationsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
